version: '3.7'

services:
    app:
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - 8080:8080
      volumes:
        - .:/var/www/html
        - logs:/var/www/logs
      command: php -S 0.0.0.0:8080 -t public


    mysql:
        platform: linux/x86_64 
        image: mysql:8
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_NAME}
        volumes:
          - database-vol:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          PMA_HOST: ${PMA_HOST}
          PMA_USER: ${PMA_USER}
          PMA_PASSWORD: ${PMA_PASSWORD}
        ports:
        - 8082:80

volumes:
    logs:
      driver: local
    database-vol:
        driver: "local"